// let name = "ROBERT";
// console.log(name);
// console.log(name);
// console.log(name);
// console.log(name);
// console.log(name);
// console.log(name);
// console.log(name);
// console.log(name);

console.log("ROBERT");
console.log("ROBERT");
console.log("ROBERT");
console.log("ROBERT");
console.log("ROBERT");
console.log("ROBERT");
console.log("ROBERT");
console.log("ROBERT");
console.log("ROBERT");
console.log("ROBERT");
